-- Find the total Customer by Countries
SELECT 
country,
COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC

-- Find total Customer by gender
SELECT 
gender,
COUNT(customer_key) total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC

-- Find total products by category 
SELECT * FROM gold.dim_products
SELECT 
category,
COUNT(product_key) total_product
FROM gold.dim_products
GROUP BY category 
ORDER BY total_product DESC 

-- What is the  averge cost in each category ??
SELECT 
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category??
SELECT * FROM gold.fact_sales
SELECT * FROM gold.dim_products
SELECT 
p.category,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revene generated by each customer??
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries??
SELECT 
c.country,
COUNT(s.quantity) sold_items
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY sold_items DESC